services:
  nginx:
    image: nginx:latest
    container_name: php-poo-nginx
    ports:
      - "80:80"
    volumes:
      - ./App:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-poo-php
    volumes:
      - ./App:/var/www/html